Repository felixrydberg/fe21-js2-miniprojekt3, pull requests merged in 2022-02, with the labels that each got.

#5 Add private cart class first commit
  modules/Cart.js
Labels: Added Feature

#6 Felix dev
  app.js
  css/style.css
  index.html
  modules/Products.js
Labels: Added Feature

#7 [Update 1] Populating index with products
  app.js
  css/style.css
  modules/Cart.js
  modules/Products.js
Labels: Added Feature

#15 Jimmy dev
  app.js
  css/style.css
  modules/Cart.js
Labels: enhancement

#18 [Update] Shoppingcart functionality fixed
  app.js
  css/style.css
  img/shopping-cart.png
  index.html
  modules/Cart.js
  modules/DB.js
Labels: Improved function

#19 [Add] Checkout added, Discount added to DB and to Cart, Product modules
  app.js
  modules/Cart.js
  modules/Patch.js
  modules/Products.js
Labels: Added Feature, Improved function

#24 [Update] closes #22 #20
  app.js
  css/style.css
  modules/Cart.js
  modules/DB.js
  modules/Patch.js
Labels: bug, Improved function

#26 Felix dev
  README.md
  app.js
  css/style.css
  index.html
Labels: documentation, Styling
